version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      SUPABASE_URL: https://your-project.supabase.co
      SUPABASE_KEY: your-secret-key
      DATABASE_URL: your-supabase-database-url  # used by Prisma
